version: "3.8"
services:

  flaskex-compose:
    build:
      context: ./
      args:
        buildno: 11042023   
    ports:
       - 5000:5000   
    expose:
      - 5000
    container_name: flaskex-down
    hostname: host
    restart: unless-stopped
    environment:
      TZ: "Europe/Moscow"
    networks:
      - default

networks:
  default:
    ipam:
      driver: default
      config:
        - subnet: 172.28.0.0/16